package in.co.exception;

public class TryFinally1 {
	public static void main(String[] args) {
		try{double div = 15/0;
		System.out.println("hello");
	}finally {
		System.out.println("java");
	}
	}

}
