package in.co.exception;

public class TryWithoutCatch {
	public static void main(String[] args) {
	try {
		int i = 34/3;
		System.out.println("hello");
	
	}
}
